var data =[{
	index:{
		nav:[{
			name:'首页',
			link:'index.html',		
		},{
			name:'双立人',
			link:'zwilling.html',
			content:[{
				title:'刀具',
				img:'../img/knife.png',
				type:[{
					name:'中式片刀',
					link:'index.html'
				},{
					name:'中式砍刀',
					link:'index.html'
				},{
					name:'果蔬刀',
					link:'index.html'
				},{
					name:'多用刀',
					link:'index.html'
				},{
					name:'刀具套餐',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'不锈钢锅具',
				img:'../img/pot.png',
				type:[{
					name:'中式炒锅',
					link:'index.html'
				},{
					name:'平底煎锅',
					link:'index.html'
				},{
					name:'汤锅/深烧锅',
					link:'index.html'
				},{
					name:'小奶锅',
					link:'index.html'
				},{
					name:'压力锅',
					link:'index.html'
				},
				{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'小家电',
				img:'../img/appliance.png',
				type:[{
					name:'多功能厨师机',
					link:'index.html'
				},{
					name:'榨汁机',
					link:'index.html'
				},{
					name:'多用料理机',
					link:'index.html'
				},{
					name:'电陶炉',
					link:'index.html'
				},{
					name:'电磁炉',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'其他',
				img:'../img/other.png',
				type:[{
					name:'西餐具刀叉',
					link:'index.html'
				},{
					name:'炊具厨房小工具',
					link:'index.html'
				},{
					name:'侍酒好物',
					link:'index.html'
				},{
					name:'玻璃器皿',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			}],
			bottom:{
				img:'../img/favicon.ico',
				link:'zwilling.html',
				title:'探索双立人'
			}
		},{
			name:'珐宝',
			link:'view/staub.html',
			content:[{
				title:'铸铁产品',
				img:'../img/nav-staub-1.png',
				type:[{
					name:'炖锅/汤锅',
					link:'index.html'
				},{
					name:'中式炒锅',
					link:'index.html'
				},{
					name:'艺术造型锅',
					link:'index.html'
				},{
					name:'茶壶',
					link:'index.html'
				},{
					name:'锅垫/防烫产品',
					link:'index.html'
				},
				{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'陶瓷产品',
				img:'../img/nav-staub-2.png',
				type:[{
					name:'迷你锅',
					link:'index.html'
				},{
					name:'碗',
					link:'index.html'
				},{
					name:'烤盘/沙拉碗',
					link:'index.html'
				},{
					name:'调味瓶罐',
					link:'index.html'
				},{
					name:'艺术造型陶瓷',
					link:'index.html'
				},
				{
					name:'查看全部',
					link:'index.html'
				}],
				bottom:{
					img:'../img/favicon.ico',
					link:'staub.html',
					title:'探索珐宝'
				}
			}]
		},{
			name:'巴拉利尼',
			link:'ballarini.html',
			content:[{
				title:'中式炒锅',
				img:'../img/nav-balla-1.png',				
			},{
				title:'平底煎锅',
				img:'../img/nav-balla-2.png',				
			},{
				title:'装饰锅',
				img:'../img/nav-balla-3.png',				
			},{
				title:'不粘锅套餐',
				img:'../img/nav-balla-4.png',				
			}]
		},{
			name:'热销分类',
			link:'hotClassify.html',
			content:[{
				title:'发现最爱',				
				type:[{
					name:'馈赠佳礼',
					link:'index.html'
				},{
					name:'花嫁婚庆',
					link:'index.html'
				},{
					name:'两人世界',
					link:'index.html'
				},{
					name:'烘焙乐趣',
					link:'index.html'
				},{
					name:'母婴时光',
					link:'index.html'
				},{
					name:'限量收藏',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'热销分类',				
				type:[{
					name:'刀具',
					link:'index.html'
				},{
					name:'不锈钢锅具',
					link:'index.html'
				},{
					name:'小家电',
					link:'index.html'
				},{
					name:'铸铁锅',
					link:'index.html'
				},{
					name:'陶瓷',
					link:'index.html'
				},{
					name:'不粘锅',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'人气No.1',				
				type:[{
					name:'../img/nav_01.png',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]
			},{
				title:'精选套餐',				
				type:[{
					name:'../img/nav_02.jpg',
					link:'index.html'
				},{
					name:'查看全部',
					link:'index.html'
				}]				
			}],
			bottom:{
				img:'../img/favicon.ico',
				link:'zwilling.html',
				title:'探索巴拉利尼'
			}
		},{
			name:'精彩双立人',
			link:'wonderZwilling.html',
			content:[{
				title:'视频专区',				
				type:[{
					name:'../img/nav_03.jpg',
					link:'index.html'
				}]
			},{
				title:'菜谱分享',				
				type:[{
					name:'../img/nav_04.png',
					link:'index.html'
				}]
			},{
				title:'达人社区',				
				type:[{
					name:'../img/nav_05.png',
					link:'index.html'
				}]
			}]
		},{
			name:'双立人故事',
			link:'zwillingStory.html',
			content:[{
				title:'最新咨询',				
				type:[{
					name:'../img/nav_06.jpg',
					link:'index.html'
				}]
			},{
				title:'品牌故事',				
				type:[{
					name:'../img/nav_07.png',
					link:'index.html'
				}]
			},{
				title:'售后服务',				
				type:[{
					name:'../img/nav_08.png',
					link:'index.html'
				}]
			}]
		},{
			name:'美食学院',
			link:'deliciousFood.html',			
		},{
			name:'../img/nav_title.png',
			link:'restaurant.html',			
		}],
		banner:['../img/pub_banner_01.jpg','../img/pub_banner_02.jpg','../img/pub_banner_03.png'],
		
	}	
},{
	ZWILLING:{
		content:{
			name:'首页',
			link:'index.html',
		}
	}
}]